name: Build QR Adder

on:
  push:
    tags:
      - 'v*.*.*'  # Only trigger when pushing tags like v1.0.0
permissions:
  contents: write
  
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller --noconfirm --clean --onefile --windowed QR_adder.py
      - uses: actions/upload-artifact@v4
        with:
          name: QR_Adder_Windows
          path: dist/QR_adder.exe
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/QR_adder.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install pyinstaller create-dmg
          pip install -r requirements.txt
          pyinstaller --noconfirm --clean --onefile --windowed QR_adder.py
          create-dmg dist/QR_adder --overwrite --dmg-title "QR_Adder" dist/
      - uses: actions/upload-artifact@v4
        with:
          name: QR_Adder_Mac_DMG
          path: dist/QR_Adder.dmg
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/QR_Adder.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller --noconfirm --clean --onefile --windowed QR_adder.py
      - uses: actions/upload-artifact@v4
        with:
          name: QR_Adder_Linux
          path: dist/QR_adder
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/QR_adder
